### ISSUE TITLE
 RxJava2 can't call AndroidSchedulers.mainThread().

### ISSUE THREAD

**Issue by TakenokoTech** [nokotech/AndroidMVVM#4]
When rewriting the ViewModel in the Usecase, it is necessary to switch to the main thread.

* Example
```
repository.getPast("2017-02-18", "USD", "JPY", Const.ReadType.PROPERTY)
    .subscribeOn(Schedulers.io())
    .observeOn(AndroidSchedulers.mainThread())
    .subscribeWith(subscriber)
```

* Error Log
```
I/--- [ Sample2_Repository.getPast ]: onSuccess called.
D/--- [ Sample2_Repository       ]: getCache called. cache = {GET_LATEST__DATE=2018/02/22 09:04:27}
I/zygote: Do partial code cache collection, code=27KB, data=29KB
I/zygote: After code cache collection, code=27KB, data=30KB
I/zygote: Increasing code cache capacity to 128KB
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: tech.takenoko.androidmvvm, PID: 28391
                  java.lang.IllegalStateException: The content of the adapter has changed but ListView did not receive a notification. Make sure the content of your adapter is not modified from a background thread, but only from the UI thread. Make sure your adapter calls notifyDataSetChanged() when its content changes. [in ListView(-1, class tech.takenoko.androidmvvm.page_sample2.Sample2_CustomListView) with Adapter(class tech.takenoko.androidmvvm.common.BaseCustomAdapter)]
                      at android.widget.ListView.layoutChildren(ListView.java:1700)
                      at android.widget.AbsListView.onLayout(AbsListView.java:2171)
                      at android.view.View.layout(View.java:19590)
                      at android.view.ViewGroup.layout(ViewGroup.java:6053)
                      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
                      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
                      at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
                      at android.view.View.layout(View.java:19590)
                      at android.view.ViewGroup.layout(ViewGroup.java:6053)
                      at android.support.constraint.ConstraintLayout.onLayout(ConstraintLayout.java:1197)
                      at android.view.View.layout(View.java:19590)
                      at android.view.ViewGroup.layout(ViewGroup.java:6053)
                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                      at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                      at android.view.View.layout(View.java:19590)
                      at android.view.ViewGroup.layout(ViewGroup.java:6053)
                      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
                      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
                      at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
                      at android.view.View.layout(View.java:19590)
                      at android.view.ViewGroup.layout(ViewGroup.java:6053)
                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                      at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                      at com.android.internal.policy.DecorView.onLayout(DecorView.java:758)
                      at android.view.View.layout(View.java:19590)
                      at android.view.ViewGroup.layout(ViewGroup.java:6053)
                      at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2484)
                      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2200)
                      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1386)
                      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6733)
                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
                      at android.view.Choreographer.doCallbacks(Choreographer.java:723)
                      at android.view.Choreographer.doFrame(Choreographer.java:658)
                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
                      at android.os.Handler.handleCallback(Handler.java:789)
                      at android.os.Handler.dispatchMessage(Handler.java:98)
                      at android.os.Looper.loop(Looper.java:164)
                      at android.app.ActivityThread.main(ActivityThread.java:6541)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
I/chatty: uid=10087(u0_a87) Binder:28391_4 identical 3 lines
E/StudioProfiler: JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
```

**Comment by TakenokoTech** [comment]
Add execute MainThread method in Usecase.

```
abstract class BaseUsecase() {

+   /* MainThreadHandler */
+   private val mHandler = Handler(Looper.getMainLooper())

+    /**
+     * execute Main Thread.
+     * @param callback
+     */
+    fun onMainThread(callback: DefaultBlock) {
+        mHandler.post { callback() }
+    }
```

* used example

```
class Sample2_Usecase @Inject constructor(): BaseUsecase() {
    fun xxxx() {
       val subscriber = object: Subscriber<XxxxxEntity>() {
-       override fun onNext(t: XxxxxEntity?) { ..... }
+       override fun onNext(t: XxxxxEntity?) { onMainThread { ..... }}
-       override fun onCompleted() { ..... }
+       override fun onCompleted() { onMainThread {.....}}
-       override fun onError(error: Throwable?) { ..... }
+       override fun onError(error: Throwable?) { onMainThread {.....}}
        }
    }
}
```
